services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf.template:/etc/nginx/nginx.conf.template:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - app_blue
      - app_green
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL}
      - PORT=${PORT}
    command: >
      sh -c "mkdir -p /var/log/nginx &&
             rm -f /var/log/nginx/access.log /var/log/nginx/error.log &&
             touch /var/log/nginx/access.log /var/log/nginx/error.log &&
             envsubst '$$ACTIVE_POOL $$PORT' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf &&
             nginx -g 'daemon off;'"
    restart: unless-stopped

  alert_watcher:
    build:
      context: .
      dockerfile: Dockerfile.watcher
    volumes:
      - nginx_logs:/var/log/nginx:ro
    environment:
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - ERROR_RATE_THRESHOLD=${ERROR_RATE_THRESHOLD:-2}
      - WINDOW_SIZE=${WINDOW_SIZE:-200}
      - ALERT_COOLDOWN_SEC=${ALERT_COOLDOWN_SEC:-300}
    depends_on:
      - nginx
    restart: unless-stopped

  app_blue:
    image: ${BLUE_IMAGE}
    ports:
      - "8081:${PORT:-3000}"
    environment:
      - APP_POOL=blue
      - RELEASE_ID=${RELEASE_ID_BLUE}
      - PORT=${PORT:-3000}
      - CHAOS_MODE=${CHAOS_MODE:-false}
      - CHAOS_ERROR_RATE=${CHAOS_ERROR_RATE:-0.5}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-3000}/healthz"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s

  app_green:
    image: ${GREEN_IMAGE}
    ports:
      - "8082:${PORT:-3000}"
    environment:
      - APP_POOL=green
      - RELEASE_ID=${RELEASE_ID_GREEN}
      - PORT=${PORT:-3000}
      - CHAOS_MODE=${CHAOS_MODE:-false}
      - CHAOS_ERROR_RATE=${CHAOS_ERROR_RATE:-0.5}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-3000}/healthz"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s

volumes:
  nginx_logs: