name: Deploy Blue/Green to Live Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to Live Server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/blue-green-deployment
          git pull origin main
          sudo docker-compose down --remove-orphans
          sudo docker-compose pull
          sudo docker-compose up -d
          sleep 15
          curl -f http://localhost:8080/version